n=input("ENter numbr 1:")
s=set()
s.add(int(n))
n=input("ENter numbr 2:")
s.add(int(n))
n=input("ENter numbr 3:")
s.add(int(n))
n=input("ENter numbr 4:")
s.add(int(n))
n=input("ENter numbr 5:")
s.add(int(n))
print(s)